package com.test.com.customer
import com.test.com.customer.UIDStats.sc
import org.apache.spark.sql.SQLContext
import org.apache.spark.{SparkConf, SparkContext}

object AadharDatasetAnalysis {
  val conf = new SparkConf().setAppName("Aadhar Data Analysis").setMaster("local")
  val sc = new SparkContext(conf)
  val sqlContext=new SQLContext(sc)

  import sqlContext. implicits._

  def main(args: Array[String]): Unit = {
    System.setProperty("hadoop.home.dir", "C:\\Hadoop\\hadoop-3.1.2")
    System.setProperty("spark.sql.warehouse.dir", "file:\\C:\\Users\\dhana\\OneDrive\\Desktop\\spark-2.4.3-bin-hadoop2.7\\spark-warehouse")
    val data=sc.textFile("C:\\Users\\dhana\\OneDrive\\Desktop\\scala_doc_dataflair\\data\\UIDAI-ENR-DETAIL-20170308.csv")

    // Reading the data and created a Dataframe
    val header= data.first()
    val aadharDataWithoutHeader = data.filter(rec => rec != header)

    val datamap = aadharDataWithoutHeader.map(rec => rec.split(","))

    val dataRDD = datamap.map(rec => caseData(rec(0), rec(1), rec(2), rec(3), rec(4), rec(5), rec(6), rec(7).toInt,
      rec(8).toInt, rec(9).toInt, rec(10).toInt, rec(11).toInt))

    val dataDF = dataRDD.toDF()

    dataDF.registerTempTable("data")

    // Reviewing the data
     sqlContext.sql("SELECT * FROM data LIMIT 10").show()

    // Getting the total and gender wise count of records
    /*sqlContext.sql("SELECT COUNT(*) FROM data WHERE Gender!='F' AND Gender!='M'").show()
    sqlContext.sql("SELECT COUNT(*) FROM data WHERE Gender!='M'").show()
    sqlContext.sql("SELECT COUNT(*) FROM data WHERE Gender!='F' AND Gender!='M'").show()*/

    // Count the number of identities(Aadhaar) generated by each Enrollment Agency and Get Top 3 agencies
   

  }

  case class caseData(Registrar: String, EnrolmentAgency: String, State: String, District: String, SubDistrict: String,
                  PinCode: String, Gender: String, Age: Int, AadharGenerated: Int, EnrolmentRejected: Int, EmailProvided: Int,
                  MobileNumProvided: Int)
}
